//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroidDal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DroidTracker
    {
        public long TrackingId { get; set; }
        public int TotalNoofPassenger { get; set; }
        public int NoofPassengerDeparted { get; set; }
        public int NoofPassengerarrived { get; set; }
        public string FromBuilding { get; set; }
        public string ToBuilding { get; set; }
        public string DateofJourney { get; set; }
    }
}
